/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercise9;

/**
 *
 * @author anna
 */
public class Ex9DriverGUI extends javax.swing.JFrame {

    /**
     * Creates new form JFrameConverter
     */
    public Ex9DriverGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionLabel = new javax.swing.JLabel();
        firstNum = new javax.swing.JTextField();
        firstUnit = new javax.swing.JComboBox<>();
        convertButton = new javax.swing.JButton();
        secondUnit = new javax.swing.JComboBox<>();
        tempLabel = new javax.swing.JLabel();
        tmpOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ex9 Converter");

        instructionLabel.setText("Enter a temperaure and unit:");

        firstNum.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                firstNumInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        firstNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNumActionPerformed(evt);
            }
        });

        firstUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Celsius", "Kelvin" }));
        firstUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstUnitActionPerformed(evt);
            }
        });

        convertButton.setText("Convert to: ");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        secondUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Celsius", "Kelvin" }));

        tempLabel.setText("Converted temp: ");

        tmpOutput.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(convertButton, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(firstNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(instructionLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tempLabel)
                                .addGap(32, 32, 32)
                                .addComponent(tmpOutput)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertButton)
                    .addComponent(secondUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempLabel)
                    .addComponent(tmpOutput))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComponents() {
        convertButton = new javax.swing.JButton();
        firstNum = new javax.swing.JTextField();
        firstUnit = new javax.swing.JComboBox<>();
        instructionLabel = new javax.swing.JLabel();
        secondUnit = new javax.swing.JComboBox<>();
        tempLabel = new javax.swing.JLabel();
        tmpOutput = new javax.swing.JLabel();
    }
    
    private void firstNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNumActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_firstNumActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        // TODO add your handling code here:
        Ex9Converter converter = new Ex9Converter();
        double firstNum = Double.parseDouble(firstNum.getText());
        double tmpOut = 0.00;
        
        if ("Fahrenheit".equals(firstUnit)) && ("Celsius".equals(secondUnit)) {
            tmpOut.setText(Double.toString(converter.f2c(firstNum)));
        }
        if ("Fahrenheit".equals(firstUnit)) && ("Kelvin".equals(secondUnit)) {
            tmpOut.setText(Double.toString(converter.f2k(firstNum)));
        }        
        if ("Fahrenheit".equals(firstUnit)) && ("Fahrenheit".equals(secondUnit)) {
            tmpOut.setText(firstNum);
        }        
        
        if ("Celsius".equals(firstUnit)) && ("Fahrenheit".equals(secondUnit)) {
            tmpOut.setText(Double.toString(converter.c2f(firstNum)));
        }
        if ("Celsius".equals(firstUnit)) && ("Kelvin".equals(secondUnit)) {
            tmpOut.setText(Double.toString(converter.c2k(firstNum)));
        }        
        if ("Celsius".equals(firstUnit)) && ("Celsius".equals(secondUnit)) {
            tmpOut.setText(firstNum);
        }
        
        if ("Kelvin".equals(firstUnit)) && ("Fahrenheit".equals(secondUnit)) {
            tmpOut.setText(Double.toString(converter.k2f(firstNum)));
        }
        if ("Kelvin".equals(firstUnit)) && ("Celsius".equals(secondUnit)) {
            tmpOut.setText(Double.toString(converter.k2c(firstNum)));
        }        
        if ("Kelvin".equals(firstUnit)) && ("Kelvin".equals(secondUnit)) {
            tmpOut.setText(firstNum);
        }        
        
    }//GEN-LAST:event_convertButtonActionPerformed

    private void firstUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstUnitActionPerformed

    private void firstNumInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_firstNumInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNumInputMethodTextChanged

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex9DriverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex9DriverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex9DriverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex9DriverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex9DriverGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertButton;
    private javax.swing.JTextField firstNum;
    private javax.swing.JComboBox<String> firstUnit;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JComboBox<String> secondUnit;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel tmpOutput;
    // End of variables declaration//GEN-END:variables
}

//        Ex9Converter convertTemp = new Ex9Converter();
//        tmpOutput.setText(" ");